/// Flutter icons WebsiteCustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WebsiteCustomIcons
///      fonts:
///       - asset: fonts/WebsiteCustomIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class WebsiteCustomIcons {
  WebsiteCustomIcons._();

  static const _kFontFam = 'WebsiteCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData linkedin = IconData(0xf08c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_square = IconData(0xf092, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discord = IconData(0xf392, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
